// Code generated by protoc-gen-go-vtproto. DO NOT EDIT.
// protoc-gen-go-vtproto version: v0.3.0
// source: dockervm_message.proto

package protogo

import (
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var vtprotoPool_DockerVMMessage = sync.Pool{
	New: func() interface{} {
		return &DockerVMMessage{}
	},
}

func (m *DockerVMMessage) ResetVT() {
	m.Reset()
}
func (m *DockerVMMessage) ReturnToVTPool() {
	if m != nil {
		m.ResetVT()
		vtprotoPool_DockerVMMessage.Put(m)
	}
}
func DockerVMMessageFromVTPool() *DockerVMMessage {
	return vtprotoPool_DockerVMMessage.Get().(*DockerVMMessage)
}
